INSERT INTO users (name, age) VALUES ("Mary", "24");
INSERT INTO users (name, age) VALUES ("Bob", "25");
INSERT INTO users (name, age) VALUES ("Harry", "24");
INSERT INTO users (name, age) VALUES ("Sarah", "27");
INSERT INTO users (name, age) VALUES ("Molly", "28");
INSERT INTO users (name, age) VALUES ("Jim", "30");
INSERT INTO users (name, age) VALUES ("Will", "26");
INSERT INTO users (name, age) VALUES ("Carla", "23");
INSERT INTO users (name, age) VALUES ("Erin", "27");
INSERT INTO users (name, age) VALUES ("Mark", "28");
INSERT INTO users (name, age) VALUES ("Chris", "32");
INSERT INTO users (name, age) VALUES ("Sue", "30");
INSERT INTO users (name, age) VALUES ("Anna", "22");
INSERT INTO users (name, age) VALUES ("Joe", "25");
INSERT INTO users (name, age) VALUES ("Jenny", "27");
INSERT INTO users (name, age) VALUES ("Brian", "29");
INSERT INTO users (name, age) VALUES ("Kyle", "26");
INSERT INTO users (name, age) VALUES ("Rich", "26");
INSERT INTO users (name, age) VALUES ("Ivy", "28");
INSERT INTO users (name, age) VALUES ("Ruby", "29");

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cat & Dog Food Drive", "Animals", 500, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Toys for Children", "Children", 125, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Meals on Wheels", "Homeless", 75, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Alzheimers Run", "Seniors", 100, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Counseling Sessions", "Domestic Violence", 65, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wig Making", "Cancer Survivors", 1000, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog Harnesses", "Blind & Deaf", 500, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Musical Instruments", "Developmental Disabilities", 315, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("PTSD Counseling", "Military", 80, "7/1/17", "7/31/17");

INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
