INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p1", "first", 10000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p2", "second", 15000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p3", "third", 20000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p4", "fourth", 25000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p5", "fifth", 30000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p6", "sixth", 35000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p7", "seventh", 40000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p8", "eigth", 45000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p9", "ninth", 50000, "12/16/2019", "1/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p10", "tenth", 55000, "12/16/2019", "1/30/2019");
INSERT INTO users (name, age) VALUES ("John", 20);
INSERT INTO users (name, age) VALUES ("Han", 19);
INSERT INTO users (name, age) VALUES ("Yoda", 200);
INSERT INTO users (name, age) VALUES ("James", 23);
INSERT INTO users (name, age) VALUES ("Jennifer", 25);
INSERT INTO users (name, age) VALUES ("Jenny", 18);
INSERT INTO users (name, age) VALUES ("Elliot", 29);
INSERT INTO users (name, age) VALUES ("Darlene", 26);
INSERT INTO users (name, age) VALUES ("Edwards", 26);
INSERT INTO users (name, age) VALUES ("Mary", 22);
INSERT INTO users (name, age) VALUES ("John", 20);
INSERT INTO users (name, age) VALUES ("Han", 19);
INSERT INTO users (name, age) VALUES ("Yoda", 200);
INSERT INTO users (name, age) VALUES ("James", 23);
INSERT INTO users (name, age) VALUES ("Jennifer", 25);
INSERT INTO users (name, age) VALUES ("Jenny", 18);
INSERT INTO users (name, age) VALUES ("Elliot", 29);
INSERT INTO users (name, age) VALUES ("Darlene", 26);
INSERT INTO users (name, age) VALUES ("Edwards", 26);
INSERT INTO users (name, age) VALUES ("Mary", 22);
INSERT INTO pledges (user_id, project_id, amount) VALUES (1,1,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2,2,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (3,3,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4,2,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5,3,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (6,1,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (7,4,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (8,5,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (9,6,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (10,7,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11,8,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12,9,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (13,10,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14,3,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (15,5,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (16,6,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (17,8,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (18,7,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (19,6,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20,4,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14,5,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4,10,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2,2,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5,1,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (15,1,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (19,2,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20,7,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20,8,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11,9,300);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12,5,300);
